# Generated by Django 4.0.7 on 2022-08-03 12:01

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='dataset',
            name='parameters',
            field=models.TextField(default={}, help_text='Параметры модели (используется как json поле)', verbose_name='Параметры'),
            preserve_default=False,
        ),
    ]
