# Generated by Django 4.0.7 on 2022-08-04 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algorithm_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithm',
            name='dt_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
    ]
